gemini.api-key=${GEMINI_APIKEY}
gemini.base-url=https://generativelanguage.googleapis.com/v1beta/openai/
gemini.model=gemini-3-flash-preview
gemini.temperature=0.5
gemini.completions-path=/chat/completions